const { initializeApp, cert } = require('firebase-admin/app');
const { getFirestore } = require('firebase-admin/firestore');

const serviceAccount = require('../tradingmanagement-c1cf4-firebase-adminsdk-fbsvc-9970ad3905.json');

initializeApp({
  credential: cert(serviceAccount)
});

const db = getFirestore();
const COMPANY_ID = 'YSACC';

async function testExRates() {
  const docRef = db.collection('companies').doc(COMPANY_ID).collection('orders').doc('YS-2026-UNK-01');
  const docSnap = await docRef.get();
  const data = docSnap.data();

  const totalUsd = data.items.reduce((acc, it) => acc + (it.qty * it.unitPrice), 0); // 25,522 (or 26,022 totalAmount)
  console.log(`totalAmount USD in doc: ${data.totalAmount}`);
  console.log(`items sales amount USD: ${totalUsd}`);

  const diff = 30746400 - 22070400; // 8,676,000
  console.log(`Difference 8,676,000 / 22,070,400 = ${8676000 / 22070400} (+39.31%)`);
  console.log(`Difference 8,676,000 / 63200 = ${8676000 / 63200}`);

  // What if 30746400 is sum of (qty * purchaseUnitPrice) for a subset of items or multiplied by exRate?
  // Let's check 22070400 * 1.3931... = 30746400
  // What if exRate 1393.1 ? 22070400 / 1380 * 1393.1?
  
  // Let's check item sales amount in KRW:
  // Item sales amount: $25,522 * 1380 = 35,220,360
  // Item sales amount: $25,522 * 1400 = 35,730,800
  // Doc totalAmount: $26,022 * 1400 = 36,430,800
  // Doc totalAmount: $26,022 * 1380 = 35,910,360
  
  // What if 30,746,400 is (22,070,400 + 8,676,000)?
  // Notice that 22,070,400 * 1.3931048... = 30,746,400
  
  // Let's check if 30,746,400 was generated by:
  // (qty * purchaseUnitPrice) for SOME matched items when includes() was used!
  // In earlier versions (v2.8.114-116), loose includes() matched OTHER items/orders as well.
}

testExRates().catch(console.error);
