import type { User, Project, Task } from '../types';

export const dummyUsers: User[] = [
  { id: 'u1', name: '김대표', role: '대표이사' },
  { id: 'u2', name: '이설계', role: '설계팀' },
  { id: 'u3', name: '박생산', role: '생산관리' },
];

export const dummyProjects: Project[] = [
  { id: 'p1', name: 'A사 신제품 개발', status: 'ACTIVE' },
  { id: 'p2', name: 'B사 공정 개선', status: 'ACTIVE' },
  { id: 'p3', name: '내부 시스템 고도화', status: 'ACTIVE' },
];

export const dummyTasks: Task[] = [
  {
    id: 't1',
    title: 'A사 신제품 1차 금형 검토',
    description: 'A사 요구사항에 맞춘 1차 금형 3D 모델링 설계 및 양산성 검토',
    status: 'IN_PROGRESS',
    type: 'PROJECT',
    scheduleType: 'SCHEDULED',
    projectId: 'p1',
    projectName: 'A사 신제품 개발',
    assigneeId: 'u2',
    assigneeName: '이설계',
    requesterId: 'u1',
    requesterName: '김대표',
    customerName: 'A사',
    importance: 'A',
    urgency: 8,
    quadrant: 'Q1',
    dueDate: '2026-05-10',
    visibility: 'PUBLIC',
    createdAt: '2026-05-01',
    createdBy: 'u1'
  },
  {
    id: 't2',
    title: '주간 생산 보고서 작성',
    description: '각 라인별 생산 실적 및 불량률 취합 보고',
    status: 'TODO',
    type: 'PERIODIC',
    scheduleType: 'PERIODIC',
    assigneeId: 'u3',
    assigneeName: '박생산',
    importance: 'B',
    urgency: 9,
    quadrant: 'Q1',
    dueDate: '2026-05-09',
    visibility: 'PUBLIC',
    createdAt: '2026-05-08',
    createdBy: 'u3'
  },
  {
    id: 't3',
    title: 'C사 긴급 고객 요청 회신',
    description: '단가 변경 및 납기일 조정 건 이메일 회신',
    status: 'IN_PROGRESS',
    type: 'DAILY',
    scheduleType: 'REQUESTED',
    assigneeId: 'u1',
    assigneeName: '김대표',
    customerName: 'C사',
    importance: 'A',
    urgency: 10,
    quadrant: 'Q1',
    dueDate: '2026-05-09',
    visibility: 'RESTRICTED',
    createdAt: '2026-05-09',
    createdBy: 'u1',
    taskAssignees: ['u1', 'u3']
  },
  {
    id: 't4',
    title: '경쟁사 B사 인수 관련 대표이사 협의 안건',
    description: '보안 유지. 인수 조건 및 리스크 분석 자료 준비',
    status: 'TODO',
    type: 'PROJECT',
    scheduleType: 'SELF',
    assigneeId: 'u1',
    assigneeName: '김대표',
    importance: 'A',
    urgency: 5,
    quadrant: 'Q2',
    dueDate: '2026-05-20',
    visibility: 'PRIVATE',
    createdAt: '2026-05-08',
    createdBy: 'u1'
  },
  {
    id: 't5',
    title: '정기 설비 점검 (라인 A)',
    description: '주기적인 설비 구동부 윤활 및 마모 상태 점검',
    status: 'DONE',
    type: 'PERIODIC',
    scheduleType: 'PERIODIC',
    assigneeId: 'u3',
    assigneeName: '박생산',
    importance: 'B',
    urgency: 4,
    quadrant: 'Q2',
    dueDate: '2026-05-08',
    visibility: 'PUBLIC',
    createdAt: '2026-05-07',
    createdBy: 'u3'
  },
  {
    id: 't6',
    title: 'B사 공정 개선 프로젝트 설계 검토',
    description: 'B사 라인 증설에 따른 신규 레이아웃 설계 리뷰',
    status: 'TODO',
    type: 'PROJECT',
    scheduleType: 'SCHEDULED',
    projectId: 'p2',
    projectName: 'B사 공정 개선',
    assigneeId: 'u2',
    assigneeName: '이설계',
    customerName: 'B사',
    importance: 'B',
    urgency: 7,
    quadrant: 'Q1',
    dueDate: '2026-05-11',
    visibility: 'PUBLIC',
    createdAt: '2026-05-05',
    createdBy: 'u2'
  },
  {
    id: 't7',
    title: '신규 입사자 PC 세팅',
    description: '다음주 출근 예정인 신규 인력 자리 및 장비 세팅',
    status: 'IN_PROGRESS',
    type: 'DELEGATED',
    scheduleType: 'REQUESTED',
    assigneeId: 'u3',
    assigneeName: '박생산',
    requesterId: 'u1',
    requesterName: '김대표',
    importance: 'C',
    urgency: 8,
    quadrant: 'Q3',
    dueDate: '2026-05-10',
    visibility: 'PUBLIC',
    createdAt: '2026-05-08',
    createdBy: 'u1'
  },
  {
    id: 't8',
    title: '설계 소프트웨어 라이선스 갱신 품의',
    description: '솔리드웍스 연간 유지보수 계약 갱신 기안 작성',
    status: 'TODO',
    type: 'DAILY',
    scheduleType: 'SELF',
    assigneeId: 'u2',
    assigneeName: '이설계',
    importance: 'B',
    urgency: 3,
    quadrant: 'Q4',
    dueDate: '2026-05-25',
    visibility: 'PUBLIC',
    createdAt: '2026-05-09',
    createdBy: 'u2'
  },
  {
    id: 't9',
    title: '임원 성과급 산정 기준 변경안 마련',
    description: '외부 노출 금지. 내년도 성과급 구조 개편 초안 작성',
    status: 'DONE',
    type: 'PROJECT',
    scheduleType: 'SCHEDULED',
    assigneeId: 'u1',
    assigneeName: '김대표',
    importance: 'A',
    urgency: 5,
    quadrant: 'Q2',
    dueDate: '2026-05-07',
    visibility: 'PRIVATE',
    createdAt: '2026-04-20',
    createdBy: 'u1'
  },
  {
    id: 't10',
    title: '부품 재고 실사 (분기별)',
    description: '창고 A, B구역 자재 실물 및 전산 대조',
    status: 'TODO',
    type: 'PERIODIC',
    scheduleType: 'PERIODIC',
    assigneeId: 'u3',
    assigneeName: '박생산',
    importance: 'B',
    urgency: 6,
    quadrant: 'Q2',
    dueDate: '2026-05-15',
    visibility: 'PUBLIC',
    createdAt: '2026-05-09',
    createdBy: 'u3'
  }
];
